### ISSUE TITLE
Include the wonderful paper "Practical Multi-fidelity Bayesian Optimization for Hyperparameter Tuning"

### ISSUE THREAD

**Issue by jon-chuang** [DataSystemsGroupUT/AutoML_Survey#1]
This should be included under the multi-fidelity setting.
https://arxiv.org/pdf/1903.04703.pdf

Also, where is ASHA? https://arxiv.org/abs/1810.05934

**Comment by jon-chuang** [comment]
Also this paper for learning curves:
https://ml.informatik.uni-freiburg.de/papers/17-ICLR-LCNet.pdf

**Comment by Hassan-Eldeeb** [comment]
Hi Jon,

Thanks for your contribution. Your recommendations will reviewed to be added.
We also recommend the following steps for formal contribution:
1. Create a branch in git and make your changes.
2. Push branch to github and issue pull request (PR).
3. Discuss the pull request.
4. We are going to review the request, and merge it to the repository.

Best regards.

**Comment by Hassan-Eldeeb** [comment]
Done!
